version: "3"

services:
  app:
    container_name: "crypto_mixer_app"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
    volumes:
      - "./source:/source"
      - "./docker_entrypoints:/entrypoints"
    entrypoint: "/entrypoints/entrypoint.sh"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - "./.env"

  db:
    container_name: "crypto_mixer_db"
    image: "postgres:latest"
    volumes:
      - "./postgresql_data:/data"
    restart: unless-stopped
    env_file:
      - "./.env"
